### ISSUE TITLE
Writing hex files?

### ISSUE THREAD

**Issue by zellerin** [takagi/intel-hex#2]
Hello,

You name your library intel-hex, and readme says it is to handle hex format, but in fact, you can only read it as far as can see.

I am now cleaning up my old hex file writing code, do you think it makes sense if I spent  some effort and merge it here (assuming you are ok with the code)?

Background: I also make pic code from lisp, but I wanted to generated hex files without gpasm step. So, I implemented only type 0 and type 1 records.

Best regards,
Tomas

**Comment by takagi** [comment]
Yes. I think it makes sense. I would like you to merge it to this repository so that I will add your name to Authors on README.

**Comment by takagi** [comment]
Closed by #3.
